import os


MAX_COURSE_ATTEMPTS = os.getenv("MAX_COURSE_ATTEMPTS", 3)
FERNET_KEY = os.getenv("FERNET_KEY")
FABMAN_API_KEY = os.getenv("FABMAN_API_KEY")
ECOMAIL_API_KEY = os.getenv("ECOMAIL_API_KEY")
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
CRONJOB_TOKEN = os.getenv("CRONJOB_TOKEN")
CLASSMARKER_WEBHOOK_SECRET = os.getenv("CLASSMARKER_WEBHOOK_SECRET")
FLASK_SECRET_KEY = os.getenv("SECRET_KEY")
VERIFY_CLASSMARKER_REQUESTS = os.getenv("VERIFY_CLASSMARKER_REQUESTS")
TRACK_TIME = os.getenv("TRACK_TIME")
DISCORD_BOT_URL = os.getenv("DISCORD_BOT_URL")
BRIDGE_SECRET = os.getenv("BRIDGE_SECRET")

# COURSES_WEB_PRIVATE_KEY = os.getenv("COURSES_WEB_PRIVATE_KEY")

# Obsolete
# MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
# FABLAB_SUPPORT_EMAIL = os.getenv("FABLAB_SUPPORT_EMAIL")

ECOMAIL_MAIL_TEMPLATES = {
    "succeed_attempt": os.getenv("ECOMAIL_TEMPLATE_ID_SUCCESS_TRAINING"),
    "failed_attempt": os.getenv("ECOMAIL_TEMPLATE_ID_FAILED_TRAINING_ATTEMPT"),
    "out_of_attempts": os.getenv("ECOMAIL_TEMPLATE_ID_TRAINING_OUT_OF_ATTEMPTS"),
    "training_expiration": os.getenv("ECOMAIL_TEMPLATE_ID_TRAINING_EXPIRATION"),
    "unexpected_error": os.getenv("ECOMAIL_TEMPLATE_ID_ERROR"),
    "locked_booking": os.getenv("ECOMAIL_TEMPLATE_ID_LOCKED_BOOKING")
}
